# This is a basic workflow to help you get started with Actions
name: CICD
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: read

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25.8'
          cache: false
      - name: Static checks
        run: ./make.sh vet

  tests:
    name: tests
    runs-on: ubuntu-22.04
    services:
      pubsub_emulator:
        image: 3apag/pubsub-emulator
        ports:
          - 8085:8232
        env:
          PUBSUB_PROJECT_ID: webdevelop-live
      postgres:
        image: postgres:18-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: invest_platform
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres -d invest_platform"
          --health-interval 1s
          --health-timeout 1s
          --health-retries 50
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25.8'
          cache: false
      - name: Run tests
        env:
          PUBSUB_EMULATOR_HOST: localhost:8085
          PUBSUB_PROJECT_ID: webdevelop-live
          DB_TYPE: postgres
          DB_HOST: 127.0.0.1
          DB_PORT: "5432"
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_DATABASE: invest_platform
          DB_APP_NAME: go_common
          DB_SSL_MODE: disable
        run: ./make.sh test

  build:
    needs:
      - lint
      - tests
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
          fetch-depth: 0

      - name: Short SHA
        id: short-sha
        run: echo "sha=$(git rev-parse --short=8 HEAD)" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          registry: cr.webdevelop.pro
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            cr.webdevelop.pro/global-torque/go-common:latest
            cr.webdevelop.pro/global-torque/go-common:latest-dev
            cr.webdevelop.pro/global-torque/go-common:${{ steps.short-sha.outputs.sha }}
